catss/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :cats
end

catss/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

catss/app/models/cat.rb
class Cat < ApplicationRecord
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validate :valid_sex, :valid_color
  
  COLORS = ['red', 'green', 'white', 'orange', 'black']
  
  def valid_sex
    errors.add(:sex, "Has to be male or female") unless self.sex == 'M' || self.sex == 'F'
  end
  
  def valid_color
    errors.add(:color, "Has to be a valid color") unless Cat.colors.include?(self.color)
  end
  
  def self.colors
    COLORS
  end
end

# Cat.new(birth_date: '2015/01/20', color: 'orange', name: 'Bob', sex: 'M', description: 'Bob is a orange cat')

catss/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

catss/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  def index
    @cats = Cat.all
    render :index
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  def create
    debugger
    cat = Cat.new(cat_params)
    if cat.save
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: 422
    end
  end
  
  def show
    @cat = Cat.find(params[:id])
    render :show
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def update
    cat = Cat.find(params[:id])
    if cat.update(cat_params)
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: 422
    end
  end
  
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

catss/app/helpers/application_helper.rb
module ApplicationHelper
end

catss/app/views/cats/_form.html.erb
<% if cat.sex == 'F'
      female = 'checked'
    else
      female = ''
    end
%>

<% button = type != :edit ? 'Add a cat' : 'Update cat' %>

<form action="<%= type == :edit ? cat_url(cat) : cats_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  
  <label>Name
    <input type="text" name="cat[name]" value="<%= cat.name %>">
  </label>
  <label>Sex
    <input type="radio" name="cat[sex]" value="M" checked> M
    <input type="radio" name="cat[sex]" value="F" <%= female %> > F
  </label>
  <label>Birthday
    <input type="date" name="cat[birth_date]" value="<%=cat.birth_date%>" min="1900-01-01" max="2018-12-31">
  </label>
  <label>Color
    <select name="cat[color]">
      <option value="--select a color--" disabled selected="selected"> --select a color-- </option> 
      <% Cat.colors.each do |color| %>
        <option  value="<%= color %>" <%= color == cat.color ? 'selected' : '' %> > <%= color %> </option>
      <% end  %>
    </select>
  </label>
  <label>Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>
  
  <input type="submit" value=" <%= button %>">
</form>

catss/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, type: :edit %>

catss/app/views/cats/index.html.erb
<ul>
  <% @cats.each do |cat| %>
  <ul>
    <li>
      <%= cat.name %>
    </li>
    
    <li>
      <a href="<%=cat_url(cat)%>"> Show Cat </a>
    </li>
  </ul>
  <% end %>
</ul>






  

catss/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, type: :new %>

catss/app/views/cats/show.html.erb
<table>
  <thead>
     <tr>
         <th colspan="2"><%= @cat.name %></th>
     </tr>
 </thead>
 
 <tbody>
   <tr>
     <td>Birthday</td>
     <td><%=@cat.birth_date%></td>
   </tr>
   <tr>
     <td>Sex</td>
     <td><%=@cat.sex%></td>
   </tr>
   <tr>
     <td>Color</td>
     <td><%=@cat.color%></td>
   </tr>
   <tr>
     <td>Description</td>
     <td><%=@cat.description%></td>
   </tr>
 </tbody>
</table>

catss/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catss</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>